name: Build

on:
  merge_group:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.2
        with:
          add-job-summary-as-pr-comment: on-failure
          cache-cleanup: on-success
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-home-cache-includes: |
            caches
            notifications
            jdks
          gradle-home-cache-excludes: |
            caches/build-cache-1

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload build reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: build-reports
          path: |
            **/build/reports/

      - name: Publish build test report
        uses: mikepenz/action-junit-report@v6
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/test-results/**/TEST-*.xml'
          annotate_only: true
          detailed_summary: true
          flaky_summary: true
          include_empty_in_summary: false
          include_time_in_summary: true

      - name: Generate and submit dependency graph
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: gradle/actions/dependency-submission@v5.0.2
        with:
          cache-read-only: true
