name: Test

on: pull_request

jobs:
  test:
    strategy:
      matrix:
        version: [ 8, 11, 17 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test --stacktrace
